
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Fri Jul 08 19:54:02 ART 2022
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "getPing", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPing", namespace = "http://ws.das.ubp.edu.ar/")

public class GetPing {


}

