<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TokenUrgenciasWSService" targetNamespace="http://ws.das.ubp.edu.ar/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.das.ubp.edu.ar/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xs:schema targetNamespace="http://ws.das.ubp.edu.ar/" version="1.0" xmlns:tns="http://ws.das.ubp.edu.ar/" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="getToken" type="tns:getToken"/>

  <xs:element name="getTokenResponse" type="tns:getTokenResponse"/>

  <xs:complexType name="getToken">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getTokenResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getTokenResponse">
    <wsdl:part name="parameters" element="tns:getTokenResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getToken">
    <wsdl:part name="parameters" element="tns:getToken">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="TokenUrgenciasWS">
    <wsdl:operation name="getToken">
      <wsdl:input name="getToken" message="tns:getToken">
    </wsdl:input>
      <wsdl:output name="getTokenResponse" message="tns:getTokenResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TokenUrgenciasWSServiceSoapBinding" type="tns:TokenUrgenciasWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getToken">
      <soap:operation soapAction="urn:GetToken" style="document"/>
      <wsdl:input name="getToken">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getTokenResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TokenUrgenciasWSService">
    <wsdl:port name="TokenUrgenciasWSPort" binding="tns:TokenUrgenciasWSServiceSoapBinding">
      <soap:address location="http://localhost:8080/UrgenciasSoap/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
